### ISSUE TITLE
Document the core infrastructure of the project

### ISSUE THREAD

**Issue by tobie** [ampproject/wg-infra#19]
See the [Tooling section](https://gist.github.com/tobie/b5ce633d2622ca4f28e8374d9de8bdf5#tooling) of the OpenJS Foundation application.

This should notably:

- include estimated cost of the infrastructure and plans for funding those (e.g. continuous funding by Google),
- list services and their costs,
- list deployed open source projects and link to their repositories,
- list custom infrastructure and link to their repositories,
- specify that the infra is under the purview of the Infra WG.

**Comment by jorydotcom** [comment]
@bnb and @kborchers from the OpenJS Foundation Cross Project Council have expressed interest in helping with this effort

**Comment by estherkim** [comment]
Hey everyone! Here's the document. Happy to take feedback or clarify any points.
https://docs.google.com/document/d/1zMyyUwu9yeJFcz9aI_GEIxWn0b10SqFQpHEtf47NHFE/edit?usp=sharing

**Comment by tobie** [comment]
That’s awesome. I can’t comment on the file itself. I have a question wrt the overall infra costs. The number we provided in the application was 100k. Can you confirm that it’s actually closer to 250k and maybe explain the discrepancy?

**Comment by estherkim** [comment]
I took 250k from a recent budgeting spreadsheet so I can confirm it's more realistic than 100k. 

As for the discrepancy, I can't say for sure. Perhaps the earlier number used data from before adding visual tests to our CI build, which was around early 2019. We also opted for additional parallel Travis jobs in 2019 and recently upgraded to faster VMs. All of these changes are reflected in the more recent number. That's my best guess!

(also I opened the doc to comments. Thanks @tobie!)

**Comment by rsimha** [comment]
@estherkim, Thanks for putting together this doc!

@tobie, is this something you'd like to see checked in as an `md` file in one of our open source repos? Or is it sufficient to have a publicly accessible doc?

**Comment by tobie** [comment]
Today, during the Foundation Onboarding WG, we agreed to share this document as a google doc with the CPC (rather than a markdown file). The reasoning was that this information was more useful to the foundation than to the project as it was essentially focused on costs. Thus the foundation could decide where to put it rather than have the WG add it to its own repository.

@jorydotcom will share it with the CPC providing additional context and cc'ing @estherkim, @rsimha, and myself (I will be sharing email addresses privately with Jory).

**Comment by tobie** [comment]
The CPC had a follow-up question which was promptly addressed by @estherkim.

Having not heard back from the CPC, I suggest we close this issue. We can always revisit if new question/issues come up.

Thanks very much for your help with this, folks!
