### ISSUE TITLE
Release infra: fail on reverted commits

### ISSUE THREAD

**Issue by dvoytenko** [ampproject/wg-infra#36]
## Describe the new feature or change to an existing feature you'd like to see

If commit was found to be problematic, it's reverted. However, it still could end up in a release branch without its revert counterpart. This would create a bad release. However, this situation is fairly easily avoidable.

## Description

Naming:
 * COMMIT - the bad commit that was reverted.
 * PR(COMMIT) - the pull request that created the bad commit.
 * REVERT - the reverting commit.
 * PR(REVERT) - the pull request that created the reverting commit.
 * BRANCH - the branch created for the release.

Once the BRANCH is created, we scan the new commits in this branch. If a COMMIT is found in this branch, there must also be REVERT. If there's no REVERT, the release should fail (or warn).

## Technicals

Let's look at the recent failure with https://github.com/ampproject/amphtml/pull/27319 and the reverting https://github.com/ampproject/amphtml/pull/27422.

It's not clear that GitHub API itself provides the data that we want. For instance, here's the reverted [commit](https://api.github.com/repos/ampproject/amphtml/git/commits/17636f5a70147c20cc8b4d75d824bd508449aef5) and [pull request](https://api.github.com/repos/ampproject/amphtml/pulls/27319). I didn't find any good information to indicate that it was reverted. Thus we may have to create a label "Reverted" and set it on the reverted pull request.

The reverting [commit](https://api.github.com/repos/ampproject/amphtml/git/commits/d328abc7e23a8253812c9354cc7382d2a11555d1) and [pull request](https://api.github.com/repos/ampproject/amphtml/pulls/27422) on the other hand provide plenty of information. Such as:
 * Commit message includes "This reverts commit 17636f5a..."
 * Pull request body includes "Reverts ampproject/amphtml#27319"
 * Default branch name is "revert-27319-..."

Thus, we could look for "Reverted" label and see if there's a matching reverting commit available.

/cc @ampproject/wg-infra

**Comment by rsimha** [comment]
In addition, based on this week's learnings, we should fail any release that contains a commit without an accompanying PR.

**Comment by rsimha** [comment]
@dvoytenko We don't use the `wg-infra` repo to track FRs, we only use it for status updates. I'm moving this issue to the `amphtml` repo.

**Edit:** Moved to https://github.com/ampproject/amphtml/issues/27771. Continue discussion there.
